#version: "3.9"
services:
  ros2:
    build:
      context: .
      dockerfile: Dockerfile
    image: ros:humble-desktop-arm64  # same tag as your locally built base
    container_name: ros2_humble
    privileged: true
    network_mode: host
    stdin_open: true
    tty: true
    devices:
      - /dev/serial0:/dev/serial0
      - /dev/ttyAMA10:/dev/ttyAMA10
    command: tail -f /dev/null
    environment:
      - GPIO_BASEADDR=0xFE000000
    volumes:
      - ./ros_ws:/ros_ws
      - /dev:/dev
      - /proc/device-tree:/proc/device-tree:ro
